# Include this file in your front application routing
# cms_front:
#     resource: '@JKCmsBundle/Resources/config/routing/front_routing.yaml'

# Articles
cms.front.article.list:
    path: /articles
    controller: JK\CmsBundle\Controller\Article\ListAction

cms.article.preview:
    path: /articles/{id}/preview
    controller: JK\CmsBundle\Controller\Article\PreviewAction
    defaults:
        modules: article

cms.front.article.show:
    path: /article/{slug}
    controller: JK\CmsBundle\Controller\Article\ShowAction

