cms.homepage:
    path: /
    controller: JK\CmsBundle\Controller\Dashboard\DashboardAction

cms.dashboard:
    path: /dashboard
    controller: JK\CmsBundle\Controller\Dashboard\DashboardAction

cms.login:
    path: /login
    controller: LAG\AdminBundle\Controller\LoginAction
    defaults:
        template: '@JKCms/security/login.html.twig'

cms.logout:
    path: /logout

cms.notification.mark_as_read:
    path: /notification/{id}/mark-as-read
    controller: JK\CmsBundle\Controller\Notification\MarkAsRead

cms.tag.create_ajax:
    path: /api/tags/create
    controller: JK\CmsBundle\Controller\Tag\CreateAjax

jk_admin:
    resource: '@LAGAdminBundle/Resources/config/routing.yaml'
    prefix: /
