services:
    _defaults:
        autowire: true
        autoconfigure: true

    JK\CmsBundle\Controller\Dashboard\DashboardAction:
        class: JK\CmsBundle\Controller\Dashboard\DashboardAction
        tags:
            - 'controller.service_arguments'
        arguments:
            $tokenStorage: '@security.token_storage'

    JK\CmsBundle\Controller\Notification\MarkAsRead:
        class: JK\CmsBundle\Controller\Notification\MarkAsRead
        tags:
            - 'controller.service_arguments'
        arguments:
            $manager: '@JK\NotificationBundle\Manager\NotificationManagerInterface'
            $router: '@Symfony\Component\Routing\RouterInterface'


    JK\CmsBundle\Controller\Tag\CreateAjax:
        tags:
            - 'controller.service_arguments'

    # Articles
    JK\CmsBundle\Controller\Article\ShowAction:
        tags:
            - 'controller.service_arguments'

    JK\CmsBundle\Controller\Article\ListAction:
        tags:
            - 'controller.service_arguments'

    JK\CmsBundle\Controller\Article\CreateAction:
        class: JK\CmsBundle\Controller\Article\CreateAction
        tags:
            - 'controller.service_arguments'
        arguments:
            - '@LAG\AdminBundle\Factory\AdminFactory'
            - '@LAG\AdminBundle\Factory\DataProviderFactory'
            - '@translator'
            - '@router'

    JK\CmsBundle\Controller\ParameterGroup\ListAction:
        tags:
            - 'controller.service_arguments'

    JK\CmsBundle\Controller\Article\UnsubscribeAction:
        tags:
            - 'controller.service_arguments'

    JK\CmsBundle\Controller\Article\SearchAction:
        tags:
            - 'controller.service_arguments'

    JK\CmsBundle\Controller\Article\PreviewAction:
        tags:
            - 'controller.service_arguments'
