services:
    _defaults:
        autowire: true
        autoconfigure: true

    JK\CmsBundle\Event\Subscriber\Menu\MenuSubscriber: ~

    JK\CmsBundle\Event\Subscriber\ParameterGroupSubscriber\ParameterGroupSubscriber: ~
