services:
    _defaults:
        autowire: true
        autoconfigure: true

    ### Form Types ###
    JK\CmsBundle\Bridge\GoogleRecaptcha\Form\Type\RecaptchaType:
        arguments:
            - '%jk_cms.recaptcha.site_key%'
        tags:
            - {name: form.type}

    JK\CmsBundle\Form\Type\TagCollectionType:
        class: JK\CmsBundle\Form\Type\TagCollectionType
        arguments:
            - '@JK\CmsBundle\Form\Transformer\TagCollectionTransformer'
        tags:
            - {name: form.type}

#    JK\CmsBundle\Form\Type\TinyMceType:
#        class: JK\CmsBundle\Form\Type\TinyMceType
#        arguments:
#            - '@LAG\AdminBundle\Assets\Registry\ScriptRegistryInterface'
#            - '@router'
#            - '@translator'
#            - '@assets.packages'
#        tags:
#            - {name: form.type}

    JK\CmsBundle\Form\Type\AddCommentType:
        class: JK\CmsBundle\Form\Type\AddCommentType
        arguments:
            - '%kernel.environment%'
        tags:
            - {name: form.type}

    JK\CmsBundle\Form\Type\CategoryType:
        class: JK\CmsBundle\Form\Type\CategoryType
        arguments:
            - '@JK\MediaBundle\Form\Transformer\JQueryUploadTransformer'
        tags:
            - {name: form.type}

    JK\CmsBundle\Form\Type\ArticleType:
        class: JK\CmsBundle\Form\Type\ArticleType
        arguments:
            - '@Symfony\Component\Routing\RouterInterface'
        tags:
            - {name: form.type}

    JK\CmsBundle\Form\Type\CommentType:
        arguments:
            - '@LAG\AdminBundle\Admin\Helper\AdminHelperInterface'
        tags:
            - {name: form.type}

    ### Form Transformers ###
    JK\CmsBundle\Form\Transformer\TagCollectionTransformer:
        class: JK\CmsBundle\Form\Transformer\TagCollectionTransformer
        arguments:
            - '@JK\CmsBundle\Repository\TagRepository'

    ### Form Validators ###
    JK\CmsBundle\Bridge\GoogleRecaptcha\Form\Validator\RecaptchaValidator:
        class: JK\CmsBundle\Bridge\GoogleRecaptcha\Form\Validator\RecaptchaValidator
        arguments:
            - '%jk_cms.recaptcha.secret%'
            - '@request_stack'
