services:
    _defaults:
        autowire: true
        autoconfigure: true

    JK\CmsBundle\Form\Handler\AddCommentHandler:
        arguments:
            $contactEmail: '%jk_cms.contact_email%'

    JK\CmsBundle\Filter\Handler\RequestFilterHandlerInterface: '@JK\CmsBundle\Filter\Handler\RequestFilterHandler'
    JK\CmsBundle\Filter\Handler\RequestFilterHandler: ~

