services:
    _defaults:
        autowire: true
        autoconfigure: true

    JK\CmsBundle\Form\Handler\AddCommentHandler:
        arguments:
            $fromEmail: '%jk_cms.email.from%'
            $toEmail: '%jk_cms.email.to%'

    JK\CmsBundle\Filter\Handler\RequestFilterHandlerInterface: '@JK\CmsBundle\Filter\Handler\RequestFilterHandler'
    JK\CmsBundle\Filter\Handler\RequestFilterHandler: ~

