services:
    JK\CmsBundle\DependencyInjection\Helper\ConfigurationHelper:
        arguments:
            $config: []

    JK\CmsBundle\Assets\AssetsHelper:
        arguments:
            $kernelEnvironment: '%kernel.environment%'
            $assetsMapping: '%jk_media.mapping%'
            $router: '@Symfony\Component\Routing\RouterInterface'
            $assetsManager: '@Liip\ImagineBundle\Imagine\Cache\CacheManager'
            $rootDirectory: '%kernel.root_dir%'

    JK\CmsBundle\Assets\ScriptRegistry:
        arguments:
            $environment: '@Twig\Environment'
            $template: '%jk_cms.scripts.template%'
