services:
    JK\CmsBundle\Install\InstallerRegistry\Registry: ~

    JK\CmsBundle\Install\Installer\AdminResourceInstaller:
        arguments:
            $projectDirectory: '%kernel.project_dir%'

    JK\CmsBundle\Install\Installer\ParametersInstaller:
        arguments:
            $groupRepository: '@JK\CmsBundle\Repository\ParameterGroupRepository'
            $parametersRepository: '@JK\CmsBundle\Repository\ParametersRepository'
