services:
    ### Managers ###
    JK\CmsBundle\Module\Manager\ModuleManager:
        arguments:
            $registry: '@JK\CmsBundle\Module\Registry\ModuleRegistryInterface'
    JK\CmsBundle\Module\Manager\ModuleManagerInterface: '@JK\CmsBundle\Module\Manager\ModuleManager'

    ### Modules ###
    JK\CmsBundle\Module\Modules\News\NewsModule:
        class: JK\CmsBundle\Module\Modules\News\NewsModule
        arguments:
            - '@JK\CmsBundle\Repository\ArticleRepository'
        tags:
            - {name: cms.module}

    ### Events ###
    JK\CmsBundle\Module\Event\Subscriber\ModuleEventSubscriber:
        class: JK\CmsBundle\Module\Event\Subscriber\ModuleEventSubscriber
        arguments:
            - '@JK\CmsBundle\Module\Manager\ModuleManager'
        tags:
            - {name: kernel.event_subscriber}

    ### Registry ###
    JK\CmsBundle\Module\Registry\ModuleRegistryInterface: '@JK\CmsBundle\Module\Registry\ModuleRegistry'

    JK\CmsBundle\Module\Registry\ModuleRegistry:
        arguments:
            - !tagged_iterator cms.module

