services:
    _defaults:
        autoconfigure: true
        autowire: true

    JK\CmsBundle\Twig\CmsExtension:
        tags:
            - {name: twig.extension}

    JK\CmsBundle\Twig\ModuleExtension:
        tags:
            - {name: twig.extension}

    JK\CmsBundle\Twig\DateExtension:
        tags:
            - {name: twig.extension}
        arguments:
            - '%kernel.default_locale%'
